### ISSUE TITLE
Semi-circle for the SPMe 

### ISSUE THREAD

**Issue by noelhallemans** [pybamm-team/pybamm-eis#18]
Hi,

Comparing EIS data of different models in compare_models.py, it appears that the SPMe does not have a semi-circle for the same electrode double-layer capacity as the other models. 

options={"surface form": "differential"} and both  positive and negative electrode double-layer capacities are set to 0.2 F m-2 for the figure below

![Screenshot 2024-07-12 at 14 31 47](https://github.com/user-attachments/assets/ea952362-6f1c-4d3e-95fd-fe0a461fcad3)

This is unexpected as the semi-circles of all models should be quite similar!

Interestingly, semi-circles for the SPMe appear when choosing the electrode double-layer capacity values unreasonably high:

100 F/m2: ![image](https://github.com/user-attachments/assets/82a8dd83-1443-4385-85e7-11a5fd813629)

compared to 0.2 F/m2: ![Screenshot 2024-07-12 at 14 38 43](https://github.com/user-attachments/assets/717aba9a-f03c-4606-936f-17fabe082d20)

This may be related to the bug in leading surface form conductivity (https://github.com/pybamm-team/PyBaMM/pull/4139), however, using the develop branch does not solve this issue.

We use PyBAMM version 24.1.

Kind regards,

Noël

**Comment by rtimms** [comment]
will be fixed by https://github.com/pybamm-team/PyBaMM/pull/4293
